Modify your 128 issue
binbat/live777 pull request #177
Opened 2024-06-17 12:26 UTC by udrs

Thank you for your great job.

2024-06-17 13:23 UTC, a-wing requested changes
Thank you very much your contribution

This commit fix #128 right?

The code need some a little change:
1. *your change upstream, you need change `Cargo.toml`
2. use `cargo fmt` format all code
3. use `cargo clippy --all-targets --all-features --workspace -- -D warnings` lint your code
4. *CLA sign

* * *
**1. your change upstream, you need change `Cargo.toml`**

your patch upstream: https://github.com/webrtc-rs/webrtc/commit/ae93e81a493c004b0270603d539ad9a40b7b3064. 

you need change `Cargo.toml`  in 

https://github.com/binbat/live777/blob/b9b397f30aa434a5b36266b9f9404beaa6549738/Cargo.toml#L21-L23

* * *

**4. CLA sign**

Please read this document and sign at the end

https://github.com/binbat/live777/blob/main/.github/CLA.md

You can reference this: https://github.com/binbat/live777/pull/95

2024-06-17 13:23 UTC, a-wing commented on liveman.toml
> +[http]
Remove this file `liveman.toml`

2024-06-17 13:23 UTC, a-wing commented on tools/whepfrom/src/main.rs
> +    //println!("Original ICE Servers:");
Remove this

2024-06-17 13:23 UTC, a-wing commented on tools/whepfrom/src/main.rs
> +    // 获取更新后的配置
English comment. please

2024-06-17 13:23 UTC, a-wing commented on tools/whepfrom/src/main.rs
> +    let updated_config = peer.get_configuration().await;
Why `get_configuration()` in here?

2024-06-17 13:23 UTC, a-wing commented on tools/whepfrom/src/main.rs
> +
Remove useless spaces

2024-06-17 13:23 UTC, a-wing commented on tools/whepfrom/src/main.rs
>      let (answer, _ice_servers) = client
`_ice_servers` is a useless variable, If you want to use this variable, rename this variable name `ice_servers`

2024-06-17 13:23 UTC, a-wing commented on tools/whepfrom/src/main.rs
> +    //for ice_server in &current_config.ice_servers {
Remove useless code

2024-06-17 13:23 UTC, a-wing commented on tools/whipinto/src/test.rs
> +#[tokio::main]
https://doc.rust-lang.org/book/ch11-01-writing-tests.html

2024-06-20 17:00 UTC, udrs commented on liveman.toml
> +[http]
Issues mentioned are solved. Thank you for your great job and check.

2024-06-20 17:00 UTC, udrs commented on tools/whepfrom/src/main.rs
> +    // 获取更新后的配置
Issues mentioned are solved. Thank you for your great job and check.

2024-06-20 17:01 UTC, udrs commented on tools/whepfrom/src/main.rs
> +    let updated_config = peer.get_configuration().await;
Verify that the configuration was updated successfully

2024-06-20 17:01 UTC, udrs commented on tools/whepfrom/src/main.rs
> +    //println!("Original ICE Servers:");
code Removed

2024-06-20 17:04 UTC, udrs commented on tools/whipinto/src/test.rs
> +#[tokio::main]
test.rs written

2024-06-20 17:09 UTC, udrs commented on tools/whepfrom/src/main.rs
> +
space removed

2024-06-20 17:18 UTC, udrs commented on tools/whepfrom/src/main.rs
>      let (answer, _ice_servers) = client
name changed

2024-06-21 08:13 UTC, udrs reviewed
set getconfiguration function and corresponding test.rs file

2024-06-21 08:40 UTC, a-wing approved these changes

2024-06-21 08:40 UTC, merged