About the index
binbat/live777 pull request #40
Opened 2023-10-18 03:18 UTC by fastfeee

I don't if it's right ,but i have no other ideas

2023-10-18 15:42 UTC, a-wing requested changes
BTW: The `start Whip` is not working.

2023-10-18 15:42 UTC, a-wing commented on assets/index.html
> +                    { rid: 'c' }
Enhanced level should include basic level

This array `sendEncodings` should append enhanced level

2023-10-18 15:42 UTC, a-wing commented on assets/index.html
> +            const stream = onPublish();
This function `onPublish` is not return any value

The stream is `undefined`

after:

<img width="473" alt="Screenshot 2023-10-18 at 23 35 10" src="https://github.com/binbat/live777/assets/18189138/d3711949-3b0f-4bfb-b68d-750805a2ba76">

2023-10-18 15:42 UTC, a-wing commented on assets/whip.js
> +        );
`whip.js` as a lib.

The lib forever shouldn't change Dom. **This is a principle**

2023-10-19 07:32 UTC, fastfeee commented
![image](https://github.com/binbat/live777/assets/122343287/961c3c34-0660-4240-bdf3-08c96f3872e7)
I dont't know why whe error occur

2023-10-20 02:39 UTC, fastfeee commented
Is there a problem with the original index？
![image](https://github.com/binbat/live777/assets/122343287/58c5df57-e1c4-46f5-b443-b2964f4eedd7)

2023-10-20 07:15 UTC, closed without merging